name-template: 'search@$NEXT_PATCH_VERSION'
tag-template: 'search@$NEXT_PATCH_VERSION'
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
      - '.github/*'
  - label: 'bug'
    branch:
      - '/bug-.+'
  - label: 'chore'
    branch:
      - '/chore-.+'
  - label: 'feature'
    branch:
      - '/feature-.+'
categories:
  - title: 'Breaking Changes'
    labels:
      - 'breakingchange'
  - title: 'üöÄ New Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'üêõ Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'üß∞ Maintenance'
    label:
      - 'chore'
      - 'maintenance'
      - 'documentation'
      - 'docs'

change-template: '- $TITLE (#$NUMBER)'
include-paths:
  - 'packages/search'
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes

  $CHANGES

  ## Contributors
  We'd like to thank all the contributors who worked on this release!

  $CONTRIBUTORS
