name: Benchmarking

on: [pull_request]

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        redis-version: [5.x, 6.x]

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Redis
        uses: shogo82148/actions-setup-redis@v1.9.7
        with:
          redis-version: ${{ matrix.redis-version }}
          auto-start: "true"

      - run: npm i --no-audit --prefer-offline
      - name: Run Benchmark
        run: npm run benchmark > benchmark-output.txt && cat benchmark-output.txt
      - name: Upload Benchmark Result
        uses: actions/upload-artifact@v2.2.2
        with:
          name: benchmark-output.txt
          path: benchmark-output.txt
